"""Small, provider-neutral semantic extraction boundary.

The model may interpret an observation.  Normalization, provenance, and
conflict handling remain deterministic in the caller.
"""

from __future__ import annotations

import json
import math
import re
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from datetime import datetime
import hashlib
from typing import Any, Protocol
from urllib import error, request

from .core.types import JSONValue


_VALUE_TYPES = frozenset({"string", "date", "datetime", "boolean", "number", "enum"})
_ROLES = frozenset({"OBSERVED", "INTENDED", "DOCUMENTED"})
_MIN_CONFIDENCE = 0.5
_FORBIDDEN_KEYS = frozenset(
    {
        "task_type", "pair_id", "category", "abstention_trigger", "contradiction",
        "evidence_a", "evidence_b", "why_contradictory", "critical_actions",
        "execution_dag", "must_yield", "reference_actions", "evaluator_outputs",
        "task_id", "should_act", "should_abstain", "gold_answer", "metadata",
    }
)


@dataclass(frozen=True, slots=True)
class Provenance:
    """Trusted provenance attached by the runtime, not generated by the model."""

    observation_id: str
    tool_name: str
    tool_arguments: JSONValue
    location: str
    excerpt: str


@dataclass(frozen=True, slots=True)
class ClaimCandidate:
    entity: str
    property: str
    value: JSONValue
    value_type: str
    role: str
    confidence: float
    provenance: Provenance


@dataclass(frozen=True, slots=True)
class ExtractionContext:
    semantic_hint: str | None = None


class SemanticExtractor(Protocol):
    def extract(
        self,
        observation: object,
        context: ExtractionContext | None = None,
    ) -> list[ClaimCandidate]:
        ...


def _json_safe(value: object) -> JSONValue:
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else str(value)
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in sorted(value.items(), key=lambda item: str(item[0]))}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if hasattr(value, "model_dump"):
        return _json_safe(value.model_dump())
    if hasattr(value, "to_dict"):
        return _json_safe(value.to_dict())
    return str(value)


def _strip_forbidden(value: object) -> JSONValue:
    if isinstance(value, Mapping):
        return {
            str(key): _strip_forbidden(item)
            for key, item in sorted(value.items(), key=lambda item: str(item[0]))
            if str(key).casefold() not in _FORBIDDEN_KEYS
        }
    if isinstance(value, (list, tuple)):
        return [_strip_forbidden(item) for item in value]
    return _json_safe(value)


def _compact(value: object, limit: int = 800) -> str:
    text = value if isinstance(value, str) else json.dumps(
        _strip_forbidden(value), ensure_ascii=False, sort_keys=True, separators=(",", ":")
    )
    return text[:limit]


def observation_provenance(observation: object, *, location: str = "tool_result") -> Provenance:
    explicit_id = getattr(observation, "observation_id", None)
    if not isinstance(explicit_id, str):
        payload = {
            "call_index": getattr(observation, "call_index", 0),
            "tool_name": getattr(observation, "tool_name", ""),
            "tool_parameters": _strip_forbidden(getattr(observation, "tool_parameters", None)),
            "tool_result": _strip_forbidden(getattr(observation, "tool_result", None)),
        }
        encoded = json.dumps(
            payload, ensure_ascii=True, sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
        explicit_id = f"observation-{hashlib.sha256(encoded).hexdigest()[:16]}"
    return Provenance(
        observation_id=explicit_id,
        tool_name=str(getattr(observation, "tool_name", "")),
        tool_arguments=_strip_forbidden(getattr(observation, "tool_parameters", None)),
        location=location,
        excerpt=_compact(getattr(observation, "tool_result", None)),
    )


def _normalize_date(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    text = value.strip()
    formats = ("%Y-%m-%d", "%m/%d/%Y", "%B %d, %Y", "%B %d %Y", "%b %d, %Y", "%b %d %Y")
    for format_string in formats:
        try:
            return datetime.strptime(text, format_string).date().isoformat()
        except ValueError:
            continue
    return None


def _normalize_datetime(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    text = value.strip()
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00")).isoformat()
    except ValueError:
        return None


def normalize_value(value: object, value_type: str) -> JSONValue | None:
    value_type = value_type.casefold()
    if value_type not in _VALUE_TYPES:
        return None
    if value_type == "string":
        return value.strip() if isinstance(value, str) and value.strip() else None
    if value_type == "enum":
        return value.strip().casefold() if isinstance(value, str) and value.strip() else None
    if value_type == "date":
        return _normalize_date(value)
    if value_type == "datetime":
        return _normalize_datetime(value)
    if value_type == "boolean":
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            lowered = value.strip().casefold()
            if lowered in {"true", "yes"}:
                return True
            if lowered in {"false", "no"}:
                return False
        return None
    if value_type == "number":
        if isinstance(value, bool):
            return None
        if isinstance(value, (int, float)) and math.isfinite(value):
            return value
        if isinstance(value, str):
            try:
                number = float(value.strip())
            except ValueError:
                return None
            return int(number) if number.is_integer() else number
    return None


def normalize_candidate(candidate: ClaimCandidate) -> ClaimCandidate | None:
    role = candidate.role.upper()
    value_type = candidate.value_type.casefold()
    if not candidate.entity.strip() or not candidate.property.strip():
        return None
    if role not in _ROLES or value_type not in _VALUE_TYPES:
        return None
    if not isinstance(candidate.confidence, (int, float)) or not math.isfinite(candidate.confidence):
        return None
    if not 0.0 <= float(candidate.confidence) <= 1.0 or float(candidate.confidence) < _MIN_CONFIDENCE:
        return None
    normalized = normalize_value(candidate.value, value_type)
    if normalized is None:
        return None
    entity = re.sub(r"\s+", " ", candidate.entity.strip())
    entity = re.sub(r"^the\s+", "", entity, flags=re.IGNORECASE)
    property_name = re.sub(r"[\s-]+", "_", candidate.property.strip().casefold())
    return ClaimCandidate(
        entity=entity,
        property=property_name,
        value=normalized,
        value_type=value_type,
        role=role,
        confidence=float(candidate.confidence),
        provenance=candidate.provenance,
    )


def normalize_candidates(candidates: list[ClaimCandidate]) -> list[ClaimCandidate]:
    result: dict[tuple[str, str, str, str], ClaimCandidate] = {}
    for candidate in candidates:
        normalized = normalize_candidate(candidate)
        if normalized is None:
            continue
        key = (
            normalized.entity,
            normalized.property,
            normalized.value_type,
            json.dumps(normalized.value, ensure_ascii=True, sort_keys=True),
        )
        result[key] = normalized
    return sorted(result.values(), key=lambda item: (item.entity, item.property, item.value_type, str(item.value)))


def _response_json(response: object) -> object:
    if isinstance(response, Mapping):
        return response
    if isinstance(response, str):
        text = response.strip()
        if text.startswith("```"):
            text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.IGNORECASE | re.DOTALL)
        return json.loads(text)
    for attribute in ("output_text", "text", "content"):
        value = getattr(response, attribute, None)
        if value is not None:
            return _response_json(value)
    choices = getattr(response, "choices", None)
    if choices:
        message = getattr(choices[0], "message", None)
        return _response_json(getattr(message, "content", message))
    raise ValueError("model response is not structured JSON")


class OpenAICompatibleExtractionClient:
    """Dependency-free Chat Completions client for structured extraction."""

    def __init__(self, api_key: str, *, base_url: str = "https://api.deepseek.com") -> None:
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")

    def __call__(self, prompt: str, model: str) -> str:
        body = json.dumps(
            {
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0,
                "response_format": {"type": "json_object"},
            }
        ).encode("utf-8")
        call = request.Request(
            f"{self.base_url}/chat/completions",
            data=body,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with request.urlopen(call, timeout=120) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except (error.HTTPError, error.URLError, TimeoutError, OSError) as exc:
            raise RuntimeError("semantic extraction provider request failed") from exc
        try:
            content = payload["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise RuntimeError("semantic extraction provider returned no content") from exc
        if not isinstance(content, str):
            raise RuntimeError("semantic extraction provider content is not text")
        return content


class LLMStructuredExtractor:
    """Minimal LLM extractor with safe parsing and deterministic provenance."""

    def __init__(self, client: Callable[..., object], *, model: str = "deepseek-v4-pro") -> None:
        self.client = client
        self.model = model
        self.last_diagnostic: str | None = None
        self.diagnostics: list[str] = []

    def _fail(self, message: str) -> list[ClaimCandidate]:
        self.last_diagnostic = message
        self.diagnostics.append(message)
        return []

    def build_prompt(self, observation: object, context: ExtractionContext | None = None) -> str:
        payload = {
            "tool_name": str(getattr(observation, "tool_name", "")),
            "tool_kind": str(getattr(observation, "tool_kind", "")),
            "tool_arguments": _strip_forbidden(getattr(observation, "tool_parameters", None)),
            "tool_result": _strip_forbidden(getattr(observation, "tool_result", None)),
        }
        hint = context.semantic_hint if context is not None else None
        safe_hint = hint.strip() if isinstance(hint, str) and hint.strip() else None
        if safe_hint and any(key in safe_hint.casefold() for key in _FORBIDDEN_KEYS):
            safe_hint = None
        hint_text = f"\nOptional semantic hint: {safe_hint}" if safe_hint else ""
        return (
            "Extract factual claims explicitly supported by this runtime observation. "
            "Do not resolve conflicts, choose a source, infer action safety, or invent facts. "
            "Return JSON with a claims array. Each claim must contain entity, property, value, "
            "value_type, role, and confidence. Supported value_type values are string, date, "
            "datetime, boolean, number, and enum. Supported roles are OBSERVED, INTENDED, "
            "and DOCUMENTED. Return an empty claims array when no useful fact is supported."
            + hint_text
            + "\nObservation:\n"
            + json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=2)
        )

    def extract(self, observation: object, context: ExtractionContext | None = None) -> list[ClaimCandidate]:
        self.last_diagnostic = None
        if not bool(getattr(observation, "success", True)):
            return self._fail("observation_failed")
        try:
            prompt = self.build_prompt(observation, context)
            try:
                response = self.client(prompt, self.model)
            except TypeError:
                response = self.client(prompt)
            payload = _response_json(response)
            if not isinstance(payload, Mapping) or not isinstance(payload.get("claims"), list):
                return self._fail("malformed_claim_schema")
            provenance = observation_provenance(observation)
            candidates: list[ClaimCandidate] = []
            for item in payload["claims"]:
                if not isinstance(item, Mapping):
                    continue
                required = ("entity", "property", "value", "value_type", "role", "confidence")
                if any(key not in item for key in required):
                    continue
                candidates.append(ClaimCandidate(provenance=provenance, **{key: item[key] for key in required}))
            normalized = normalize_candidates(candidates)
            if not normalized and payload["claims"]:
                return self._fail("no_acceptable_claims")
            return normalized
        except Exception as exc:
            return self._fail(f"extraction_error:{type(exc).__name__}")


__all__ = [
    "ClaimCandidate",
    "ExtractionContext",
    "LLMStructuredExtractor",
    "OpenAICompatibleExtractionClient",
    "Provenance",
    "SemanticExtractor",
    "normalize_candidate",
    "normalize_candidates",
    "normalize_value",
    "observation_provenance",
]
