"""Small, provider-neutral semantic extraction boundary.

The model may interpret an observation. Normalization, provenance, and
governance state transitions remain deterministic in the caller.
"""

from __future__ import annotations

import hashlib
import json
import math
import re
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol
from urllib import error, request

try:  # Optional: the AgentAbstain runtime already provides HTTPX.
    import httpx
except ImportError:  # pragma: no cover - exercised only in minimal installs.
    httpx = None  # type: ignore[assignment]

from .core.types import JSONValue, TemporalScope


_VALUE_TYPES = frozenset({"string", "date", "datetime", "boolean", "number", "enum"})
_ROLES = frozenset({"OBSERVED", "INTENDED", "DOCUMENTED"})
_MIN_CONFIDENCE = 0.5
_FORBIDDEN_KEYS = frozenset(
    {
        "task_type", "pair_id", "abstention_trigger", "contradiction",
        "evidence_a", "evidence_b", "why_contradictory", "critical_actions",
        "execution_dag", "must_yield", "reference_actions", "evaluator_outputs",
        "should_act", "should_abstain", "gold_answer",
    }
)


@dataclass(frozen=True, slots=True)
class Provenance:
    """Trusted provenance attached by the runtime, not generated by the model."""

    observation_id: str
    tool_name: str
    tool_arguments: JSONValue
    location: str
    excerpt: str


@dataclass(frozen=True, slots=True)
class ClaimCandidate:
    entity: str
    property: str
    value: JSONValue
    value_type: str
    role: str
    confidence: float
    provenance: Provenance
    temporal_scope: str | None = None
    observed_at: str | None = None
    valid_from: str | None = None
    valid_until: str | None = None


@dataclass(frozen=True, slots=True)
class ExtractionContext:
    semantic_hint: str | None = None


class SemanticExtractor(Protocol):
    def extract(
        self,
        observation: object,
        context: ExtractionContext | None = None,
    ) -> list[ClaimCandidate]:
        ...


class SemanticModelClient(Protocol):
    """One explicit model boundary shared by semantic runtime components."""

    def complete(self, prompt: str, *, model: str) -> object:
        ...


@dataclass(frozen=True, slots=True)
class SemanticCompletion:
    """Provider content plus bounded, non-sensitive response metadata."""

    content: str
    finish_reason: str | None = None
    usage: JSONValue = None
    model: str | None = None

    @property
    def response_content_present(self) -> bool:
        return bool(self.content)


@dataclass(frozen=True, slots=True)
class SemanticInferenceConfig:
    """Low-cost provider settings for governance, separate from the Agent model."""

    max_output_tokens: int | None = 256
    thinking: bool | None = None
    reasoning_effort: str | None = None

    def __post_init__(self) -> None:
        if self.max_output_tokens is not None and self.max_output_tokens <= 0:
            raise ValueError("max_output_tokens must be positive or None")


def _json_safe(value: object) -> JSONValue:
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else str(value)
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in sorted(value.items(), key=lambda item: str(item[0]))}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if hasattr(value, "model_dump"):
        return _json_safe(value.model_dump())
    if hasattr(value, "to_dict"):
        return _json_safe(value.to_dict())
    return str(value)


def sanitize_runtime_value(value: object) -> JSONValue:
    if isinstance(value, Mapping):
        return {
            str(key): sanitize_runtime_value(item)
            for key, item in sorted(value.items(), key=lambda item: str(item[0]))
            if str(key).casefold() not in _FORBIDDEN_KEYS
        }
    if isinstance(value, (list, tuple)):
        return [sanitize_runtime_value(item) for item in value]
    return _json_safe(value)


def _compact(value: object, limit: int = 800) -> str:
    text = value if isinstance(value, str) else json.dumps(
        sanitize_runtime_value(value), ensure_ascii=False, sort_keys=True, separators=(",", ":")
    )
    return text[:limit]


def _response_preview(value: object, limit: int = 400) -> str:
    """Return a bounded preview with common credential-shaped text redacted."""

    text = value if isinstance(value, str) else _compact(value, limit)
    text = re.sub(r"Bearer\s+[A-Za-z0-9._~-]+", "Bearer [REDACTED]", text, flags=re.IGNORECASE)
    text = re.sub(r"sk-[A-Za-z0-9_-]+", "sk-[REDACTED]", text)
    text = re.sub(r"(?i)(api[_ -]?key\s*[:=]\s*)[^,\s]+", r"\1[REDACTED]", text)
    return text[:limit]


def observation_provenance(observation: object, *, location: str = "tool_result") -> Provenance:
    explicit_id = getattr(observation, "observation_id", None)
    if not isinstance(explicit_id, str):
        payload = {
            "call_index": getattr(observation, "call_index", 0),
            "tool_name": getattr(observation, "tool_name", ""),
            "tool_parameters": sanitize_runtime_value(getattr(observation, "tool_parameters", None)),
            "tool_result": sanitize_runtime_value(getattr(observation, "tool_result", None)),
        }
        encoded = json.dumps(
            payload, ensure_ascii=True, sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
        explicit_id = f"observation-{hashlib.sha256(encoded).hexdigest()[:16]}"
    return Provenance(
        observation_id=explicit_id,
        tool_name=str(getattr(observation, "tool_name", "")),
        tool_arguments=sanitize_runtime_value(getattr(observation, "tool_parameters", None)),
        location=location,
        excerpt=_compact(getattr(observation, "tool_result", None)),
    )


def _normalize_date(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    text = value.strip()
    formats = ("%Y-%m-%d", "%m/%d/%Y", "%B %d, %Y", "%B %d %Y", "%b %d, %Y", "%b %d %Y")
    for format_string in formats:
        try:
            return datetime.strptime(text, format_string).date().isoformat()
        except ValueError:
            continue
    return None


def _normalize_datetime(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    text = value.strip()
    try:
        return datetime.fromisoformat(text.replace("Z", "+00:00")).isoformat()
    except ValueError:
        return None


def normalize_value(value: object, value_type: str) -> JSONValue | None:
    value_type = value_type.casefold()
    if value_type not in _VALUE_TYPES:
        return None
    if value_type == "string":
        return value.strip() if isinstance(value, str) and value.strip() else None
    if value_type == "enum":
        return value.strip().casefold() if isinstance(value, str) and value.strip() else None
    if value_type == "date":
        return _normalize_date(value)
    if value_type == "datetime":
        return _normalize_datetime(value)
    if value_type == "boolean":
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            lowered = value.strip().casefold()
            if lowered in {"true", "yes"}:
                return True
            if lowered in {"false", "no"}:
                return False
        return None
    if value_type == "number":
        if isinstance(value, bool):
            return None
        if isinstance(value, (int, float)) and math.isfinite(value):
            return value
        if isinstance(value, str):
            try:
                number = float(value.strip())
            except ValueError:
                return None
            return int(number) if number.is_integer() else number
    return None


def normalize_candidate(candidate: ClaimCandidate) -> ClaimCandidate | None:
    role = candidate.role.upper()
    value_type = candidate.value_type.casefold()
    if not candidate.entity.strip() or not candidate.property.strip():
        return None
    if role not in _ROLES or value_type not in _VALUE_TYPES:
        return None
    if not isinstance(candidate.confidence, (int, float)) or not math.isfinite(candidate.confidence):
        return None
    if not 0.0 <= float(candidate.confidence) <= 1.0 or float(candidate.confidence) < _MIN_CONFIDENCE:
        return None
    timestamps = (candidate.observed_at, candidate.valid_from, candidate.valid_until)
    if any(value is not None and not isinstance(value, str) for value in timestamps):
        return None
    normalized = normalize_value(candidate.value, value_type)
    if normalized is None:
        return None
    entity = re.sub(r"\s+", " ", candidate.entity.strip())
    entity = re.sub(r"^the\s+", "", entity, flags=re.IGNORECASE)
    semantic_dimension = re.sub(r"\s+", " ", candidate.property.strip())
    temporal_scope = None
    if candidate.temporal_scope is not None:
        try:
            temporal_scope = TemporalScope(str(candidate.temporal_scope).upper()).value
        except ValueError:
            return None
    return ClaimCandidate(
        entity=entity,
        property=semantic_dimension,
        value=normalized,
        value_type=value_type,
        role=role,
        confidence=float(candidate.confidence),
        provenance=candidate.provenance,
        temporal_scope=temporal_scope,
        observed_at=candidate.observed_at,
        valid_from=candidate.valid_from,
        valid_until=candidate.valid_until,
    )


def normalize_candidates(candidates: list[ClaimCandidate]) -> list[ClaimCandidate]:
    result: dict[tuple[str, str, str, str], ClaimCandidate] = {}
    for candidate in candidates:
        normalized = normalize_candidate(candidate)
        if normalized is None:
            continue
        key = (
            normalized.entity,
            normalized.property,
            normalized.value_type,
            json.dumps(normalized.value, ensure_ascii=True, sort_keys=True),
        )
        result[key] = normalized
    return sorted(result.values(), key=lambda item: (item.entity, item.property, item.value_type, str(item.value)))


def parse_semantic_response(response: object) -> object:
    if isinstance(response, Mapping):
        return response
    if isinstance(response, str):
        text = response.strip()
        if text.startswith("```"):
            text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.IGNORECASE | re.DOTALL)
        return json.loads(text)
    for attribute in ("output_text", "text", "content"):
        value = getattr(response, attribute, None)
        if value is not None:
            return parse_semantic_response(value)
    choices = getattr(response, "choices", None)
    if choices:
        message = getattr(choices[0], "message", None)
        return parse_semantic_response(getattr(message, "content", message))
    raise ValueError("model response is not structured JSON")


class OpenAICompatibleExtractionClient:
    """Dependency-free Chat Completions client for structured extraction."""

    def __init__(
        self,
        api_key: str,
        *,
        base_url: str = "https://api.deepseek.com",
        timeout: float = 60.0,
        inference: SemanticInferenceConfig | None = None,
    ) -> None:
        if timeout <= 0:
            raise ValueError("timeout must be positive")
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.inference = inference or SemanticInferenceConfig()

    def complete(self, prompt: str, *, model: str) -> SemanticCompletion:
        payload: dict[str, object] = {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0,
            "response_format": {"type": "json_object"},
        }
        if self.inference.max_output_tokens is not None:
            payload["max_tokens"] = self.inference.max_output_tokens
        if self.inference.thinking is not None:
            payload["thinking"] = {"type": "enabled" if self.inference.thinking else "disabled"}
        if self.inference.reasoning_effort is not None:
            payload["reasoning_effort"] = self.inference.reasoning_effort
        body = json.dumps(payload).encode("utf-8")
        url = f"{self.base_url}/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        try:
            if httpx is not None:
                # HTTPX is also the transport used by the Agent SDK and handles
                # DeepSeek's TLS endpoint reliably. Keep this optional so the
                # core package remains dependency-light outside that runtime.
                timeout = httpx.Timeout(
                    self.timeout,
                    connect=self.timeout,
                    read=self.timeout,
                    write=self.timeout,
                    pool=self.timeout,
                )
                # The semantic endpoint is supplied explicitly. Do not inherit
                # ambient proxy configuration: malformed NO_PROXY entries (for
                # example an IPv6 loopback entry) can make HTTPX reject a valid
                # DeepSeek URL before it opens a connection.
                with httpx.Client(timeout=timeout, trust_env=False) as client:
                    response = client.post(url, content=body, headers=headers)
                    response.raise_for_status()
                    payload = response.json()
            else:
                call = request.Request(url, data=body, headers=headers, method="POST")
                with request.urlopen(call, timeout=self.timeout) as response:
                    payload = json.loads(response.read().decode("utf-8"))
        except Exception as exc:
            if httpx is not None and isinstance(exc, httpx.HTTPError):
                raise SemanticProviderError(
                    "semantic extraction provider request failed",
                    metadata={"provider_error_category": "HTTP_ERROR"},
                ) from exc
            if httpx is None or isinstance(exc, (error.HTTPError, error.URLError, TimeoutError, OSError)):
                raise SemanticProviderError(
                    "semantic extraction provider request failed",
                    metadata={"provider_error_category": "TRANSPORT_ERROR"},
                ) from exc
            raise
        try:
            content = payload["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise SemanticProviderError(
                "semantic extraction provider returned no content",
                metadata={
                    "provider_error_category": "MALFORMED_RESPONSE",
                    "response_content_present": False,
                },
            ) from exc
        if not isinstance(content, str):
            raise SemanticProviderError(
                "semantic extraction provider content is not text",
                metadata={
                    "provider_error_category": "NON_TEXT_CONTENT",
                    "response_content_present": False,
                },
            )
        choice = payload["choices"][0]
        usage = payload.get("usage")
        return SemanticCompletion(
            content=content,
            finish_reason=choice.get("finish_reason") if isinstance(choice, Mapping) else None,
            usage=sanitize_runtime_value(usage),
            model=payload.get("model") if isinstance(payload.get("model"), str) else model,
        )


class SemanticProviderError(RuntimeError):
    """Provider failure carrying only safe diagnostic metadata."""

    def __init__(self, message: str, *, metadata: Mapping[str, JSONValue] | None = None) -> None:
        super().__init__(message)
        self.metadata = dict(metadata or {})


def _response_metadata(response: object) -> dict[str, JSONValue]:
    if isinstance(response, SemanticCompletion):
        return {
            "finish_reason": response.finish_reason,
            "content_length": len(response.content),
            "response_content_present": response.response_content_present,
            "usage": response.usage,
            "model": response.model,
            "response_preview": _response_preview(response.content),
        }
    if isinstance(response, str):
        return {
            "finish_reason": None,
            "content_length": len(response),
            "response_content_present": bool(response),
            "response_preview": _response_preview(response),
        }
    if isinstance(response, Mapping):
        encoded = json.dumps(response, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        return {
            "finish_reason": None,
            "content_length": len(encoded),
            "response_content_present": True,
            "response_preview": _response_preview(encoded),
        }
    return {
        "finish_reason": None,
        "content_length": 0,
        "response_content_present": False,
        "response_preview": _response_preview(response),
    }


def _looks_truncated(text: str) -> bool:
    stripped = text.rstrip()
    if not stripped:
        return False
    if stripped.endswith(("{", "[", ",", ":")):
        return True
    return stripped.count("{") > stripped.count("}") or stripped.count("[") > stripped.count("]")


def _diagnostic(
    category: str,
    *,
    metadata: Mapping[str, JSONValue] | None = None,
    exception: BaseException | None = None,
) -> dict[str, JSONValue]:
    result: dict[str, JSONValue] = {"category": category}
    result.update(metadata or {})
    if exception is not None:
        result["exception"] = type(exception).__name__
        result["detail"] = str(exception)[:240]
    return result


class LLMStructuredExtractor:
    """Minimal LLM extractor with safe parsing and deterministic provenance."""

    def __init__(
        self,
        client: SemanticModelClient,
        *,
        model: str = "deepseek-v4-pro",
    ) -> None:
        self.client = client
        self.model = model
        self.last_diagnostic: dict[str, JSONValue] | None = None
        self.last_response_metadata: dict[str, JSONValue] = {}
        self.response_diagnostics: list[dict[str, JSONValue]] = []
        self.diagnostics: list[dict[str, JSONValue]] = []

    def _fail(self, diagnostic: dict[str, JSONValue]) -> list[ClaimCandidate]:
        self.last_diagnostic = diagnostic
        self.diagnostics.append(diagnostic)
        return []

    def build_prompt(self, observation: object, context: ExtractionContext | None = None) -> str:
        payload = {
            "tool_name": str(getattr(observation, "tool_name", "")),
            "tool_kind": str(getattr(observation, "tool_kind", "")),
            "tool_arguments": sanitize_runtime_value(getattr(observation, "tool_parameters", None)),
            "tool_result": sanitize_runtime_value(getattr(observation, "tool_result", None)),
        }
        hint = context.semantic_hint if context is not None else None
        safe_hint = hint.strip() if isinstance(hint, str) and hint.strip() else None
        if safe_hint and any(key in safe_hint.casefold() for key in _FORBIDDEN_KEYS):
            safe_hint = None
        hint_text = f"\nOptional semantic hint: {safe_hint}" if safe_hint else ""
        return (
            "Extract factual claims explicitly supported by this runtime observation. "
            "Do not resolve conflicts, choose a source, infer action safety, or invent facts. "
            "Return JSON with a claims array. Each claim must contain entity, property, value, "
            "value_type, role, and confidence. Supported value_type values are string, date, "
            "datetime, boolean, number, and enum. Supported roles are OBSERVED, INTENDED, "
            "and DOCUMENTED. temporal_scope may be CURRENT, FUTURE, HISTORICAL, INTERVAL, "
            "or UNKNOWN. Include observed_at, valid_from, or valid_until only when the "
            "observation states them explicitly. Return an empty claims array when no useful "
            "fact is supported."
            + hint_text
            + "\nObservation:\n"
            + json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=2)
        )

    def extract(self, observation: object, context: ExtractionContext | None = None) -> list[ClaimCandidate]:
        self.last_diagnostic = None
        self.last_response_metadata = {}
        if not bool(getattr(observation, "success", True)):
            return self._fail({"category": "PROVIDER_ERROR", "detail": "observation_failed"})
        try:
            prompt = self.build_prompt(observation, context)
            response = self.client.complete(prompt, model=self.model)
        except Exception as exc:
            metadata = getattr(exc, "metadata", {})
            self.last_response_metadata = dict(metadata)
            self.response_diagnostics.append(dict(metadata))
            return self._fail(_diagnostic("PROVIDER_ERROR", metadata=metadata, exception=exc))
        metadata = _response_metadata(response)
        self.last_response_metadata = metadata
        self.response_diagnostics.append(metadata)
        if not metadata["response_content_present"]:
            category = (
                "TRUNCATED_JSON"
                if metadata.get("finish_reason") == "length"
                else "EMPTY_CONTENT"
            )
            return self._fail(_diagnostic(category, metadata=metadata))
        raw_text = response.content if isinstance(response, SemanticCompletion) else response
        if not isinstance(raw_text, (str, Mapping)):
            return self._fail(_diagnostic("PROVIDER_ERROR", metadata=metadata))
        try:
            payload = parse_semantic_response(response)
        except Exception as exc:
            category = "TRUNCATED_JSON" if (
                metadata.get("finish_reason") == "length" or _looks_truncated(raw_text)
            ) else "INVALID_JSON"
            return self._fail(_diagnostic(category, metadata=metadata, exception=exc))
        if not isinstance(payload, Mapping) or not isinstance(payload.get("claims"), list):
            return self._fail(_diagnostic("INVALID_SCHEMA", metadata=metadata))
        provenance = observation_provenance(observation)
        candidates: list[ClaimCandidate] = []
        for item in payload["claims"]:
            if not isinstance(item, Mapping):
                return self._fail(_diagnostic("INVALID_SCHEMA", metadata=metadata))
            required = ("entity", "property", "value", "value_type", "role", "confidence")
            if any(key not in item for key in required):
                return self._fail(_diagnostic("INVALID_SCHEMA", metadata=metadata))
            optional = {
                key: item[key]
                for key in ("temporal_scope", "observed_at", "valid_from", "valid_until")
                if key in item
            }
            candidates.append(ClaimCandidate(
                provenance=provenance,
                **{key: item[key] for key in required},
                **optional,
            ))
        normalized = normalize_candidates(candidates)
        if not normalized and payload["claims"]:
            return self._fail(_diagnostic("NORMALIZATION_REJECTED", metadata=metadata))
        return normalized


__all__ = [
    "ClaimCandidate",
    "ExtractionContext",
    "LLMStructuredExtractor",
    "OpenAICompatibleExtractionClient",
    "Provenance",
    "SemanticExtractor",
    "SemanticInferenceConfig",
    "SemanticModelClient",
    "SemanticCompletion",
    "SemanticProviderError",
    "normalize_candidate",
    "normalize_candidates",
    "normalize_value",
    "observation_provenance",
    "parse_semantic_response",
    "sanitize_runtime_value",
]
